=pod

=head1 NAME

Starch::Plugin - Starch plugin framework.

=head1 DESCRIPTION

See L<Starch::Manual/PLUGINS> for instructions on using plugins and a
list of available plugins.

See L<Starch::Manual::Extending/PLUGINS> for instructions on writing
your own plugins.

=head1 AUTHORS AND LICENSE

See L<Starch/AUTHOR>, L<Starch/CONTRIBUTORS>, and L<Starch/LICENSE>.

=cut
